"use client";

import { OnSaveContext } from "@/context/OnSaveContext";
import { extractHtmlContent } from "@/lib/html-utils";
import { useParams, useSearchParams } from "next/navigation";
import ChatSection from "../_components/ChatSection";
import CodeSandboxWorkSpace from "../_components/CodeSandboxWorkSpace";
import PlaygroundHeader from "../_components/PlaygroundHeader";
import axios from "axios";
import { useCallback, useContext, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

export type Messages = {
  role: string;
  content: string;
  image?: string;
};

const DesignInstructions = `
Instructions:

1. If the user input explicitly requests generating code, UI layout, webpage design, or HTML/CSS/JS output (e.g., "Create a landing page", "Build a dashboard", "Generate a Tailwind CSS website"), then follow ALL the rules below:

   **General Design Requirements:**
   - Generate complete HTML code using **Tailwind CSS with Flowbite UI components**.
   - Include only the <body> content — **do NOT include <head>, <html>, or <title> tags**.
   - Apply a **modern, professional design** using **blue as the primary theme color** consistently across all components.
   - The design MUST be **fully responsive across mobile phones, tablets, and desktop devices**.
   - Ensure **clean spacing, consistent padding, modern typography, and visual hierarchy**.
   - Each section or component must be **independent** and not rely on other sections unless explicitly requested.

   **Media & Image Requirements:**
   - Use placeholder images with alt text:
       - Light Mode: https://community.softr.io/uploads/db9110/original/2X/7/74e6e7e382d0ff5d7773ca9a87e6f6f8817a68a6.jpeg
       - Dark Mode: https://www.cibaky.com/wp-content/uploads/2015/12/placeholder-3.jpg
   - Use descriptive alt attributes such as alt="placeholder image for product section".

   **Technology & Components:**
   - Use:
       - Flowbite UI components (buttons, alerts, modals, forms, cards, tables, navigation, etc.)
       - FontAwesome icons (class format: "fa fa-<icon-name>")
       - Chart.js for charts with theme-consistent styling
       - Swiper.js for sliders/carousels
       - Tippy.js for tooltips
   - Include interactive UI elements such as dropdowns, accordions, tabs, sliders, and modals wherever suitable.
   - Ensure charts and components are styled to follow the blue theme color without breaking responsiveness.

   **Design & UX Rules:**
   - Use clear visual hierarchy (headings, subheadings, text spacing).
   - Buttons must use Tailwind + Flowbite and follow the primary color scheme.
   - Navigation menus should be well-spaced and aligned horizontally on desktop and collapsible on mobile.
   - Do not include broken links or dummy "#" links—use proper placeholders such as "javascript:void(0)".
   - Ensure every section has sufficient padding (min. py-8) and modern layout structure.

   **IMPORTANT:**
   - Do NOT include any introductory or explanatory text in the output.
   - Directly output only the HTML code starting from the content inside <body>.
   - Code must be production-ready, visually appealing, and professionally structured.
   - When existing website code is provided, **modify and extend it** based on the user's request. Preserve existing sections unless the user asks to remove or replace them.

2. If the user input is casual, general, or not explicitly requesting code generation (e.g., "Hello", "How are you?", "Tell me about Tailwind CSS"), then:
   - Respond with a friendly conversational message and **do NOT generate any code**.
`;

const Project = () => {
  const { projectId } = useParams();
  const params = useSearchParams();
  const frameId = params.get("frameId");
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [messages, setMessages] = useState<Messages[]>([]);
  const [generatedCode, setGeneratedCode] = useState("");
  const hasAutoGenerated = useRef(false);
  const saveContext = useContext(OnSaveContext);

  useEffect(() => {
    hasAutoGenerated.current = false;
    if (frameId) GetFrameDetails();
  }, [frameId]);

  const SaveMessages = async (msgs: Messages[]) => {
    if (!frameId) return;
    await axios.put("/api/chats", {
      frameId: String(frameId),
      messages: msgs,
    });
  };

  const SaveGeneratedCode = async (code: string) => {
    const cleanCode = extractHtmlContent(code);
    await axios.put("/api/frames", {
      frameId: String(frameId),
      designCode: cleanCode,
      projectId,
    });
    return cleanCode;
  };

  const GenerateResponse = async (
    currentMessages: Messages[],
    existingCode = generatedCode,
  ) => {
    setLoading(true);

    try {
      const apiMessages: Messages[] = [];

      if (existingCode) {
        apiMessages.push({
          role: "system",
          content: `Existing website code to continue/modify:\n\`\`\`html\n${extractHtmlContent(existingCode)}\n\`\`\``,
        });
      }

      apiMessages.push({ role: "system", content: DesignInstructions });

      for (const msg of currentMessages) {
        apiMessages.push({ role: msg.role, content: msg.content });
      }

      const lastUserWithImage = [...currentMessages]
        .reverse()
        .find((m) => m.role === "user" && m.image);

      const response = await fetch("/api/ai-model", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: apiMessages,
          imageUrl: lastUserWithImage?.image,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        throw new Error(errorData?.error || "Failed to generate design");
      }

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No response stream");

      const decoder = new TextDecoder();

      let aiResponse = "";
      let codeContent = "";
      let isCode = false;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        aiResponse += chunk;

        if (!isCode && aiResponse.includes("```html")) {
          isCode = true;
          const index = aiResponse.indexOf("```html") + 7;
          codeContent = aiResponse.slice(index);
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        } else if (!isCode && /<\w+[^>]*>/.test(aiResponse)) {
          isCode = true;
          codeContent = aiResponse;
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        } else if (isCode) {
          if (chunk.includes("```")) {
            const endIdx = chunk.indexOf("```");
            codeContent += chunk.slice(0, endIdx);
          } else {
            codeContent += chunk;
          }
          setGeneratedCode(extractHtmlContent(codeContent) || codeContent);
        }
      }

      if (!isCode) {
        const finalMessages = [
          ...currentMessages,
          { role: "assistant", content: aiResponse },
        ];
        setMessages(finalMessages);
        await SaveMessages(finalMessages);
      } else {
        const cleanCode = extractHtmlContent(codeContent);
        setGeneratedCode(cleanCode);
        const finalMessages = [
          ...currentMessages,
          { role: "assistant", content: "Your design has been updated." },
        ];
        setMessages(finalMessages);
        await SaveGeneratedCode(cleanCode);
        await SaveMessages(finalMessages);
      }
    } catch (error) {
      console.error("Generation failed:", error);
      toast.error(
        error instanceof Error ? error.message : "Failed to generate design.",
      );
    } finally {
      setLoading(false);
    }
  };

  const GetFrameDetails = async () => {
    try {
      const result = await axios.get(
        `/api/frames?frameId=${frameId}&projectId=${projectId}`,
      );
      const chatMessages = result.data?.chatMessages ?? [];
      const designCode = extractHtmlContent(result.data?.designCode);
      setMessages(chatMessages);
      setGeneratedCode(designCode);

      const needsGeneration =
        chatMessages.length > 0 &&
        !designCode &&
        chatMessages[chatMessages.length - 1]?.role === "user" &&
        !hasAutoGenerated.current;

      if (needsGeneration) {
        hasAutoGenerated.current = true;
        await GenerateResponse(chatMessages, designCode);
      }
    } catch (error) {
      console.error("Failed to load frame:", error);
      if (axios.isAxiosError(error) && error.response?.status === 404) {
        toast.error("Project not found. Please create a new one.");
      }
    }
  };

  const HandleSave = useCallback(async () => {
    if (!frameId) return;
    setSaving(true);
    try {
      const liveDesign =
        saveContext?.getDesignHtml() ?? generatedCode;
      const designToSave = liveDesign
        ? extractHtmlContent(liveDesign)
        : "";

      await SaveMessages(messages);

      if (designToSave) {
        await SaveGeneratedCode(designToSave);
        setGeneratedCode(designToSave);
      }

      toast.success("Project saved successfully!");
    } catch (error) {
      console.error("Save failed:", error);
      toast.error("Failed to save project.");
    } finally {
      setSaving(false);
    }
  }, [frameId, messages, generatedCode, projectId, saveContext]);

  const SendMessage = async (userInput: string) => {
    const userMessage: Messages = { role: "user", content: userInput };
    const messagesWithUser = [...messages, userMessage];

    setMessages(messagesWithUser);

    try {
      await SaveMessages(messagesWithUser);
    } catch (error) {
      console.error("Failed to save message:", error);
      toast.error("Failed to save message.");
    }

    await GenerateResponse(messagesWithUser);
  };

  return (
    <div className="flex h-screen flex-col overflow-hidden">
      <PlaygroundHeader onSave={HandleSave} saving={saving} />

      <div className="flex min-h-0 flex-1 overflow-hidden">
        <ChatSection
          messages={messages}
          onSend={(input: string) => SendMessage(input)}
          loading={loading}
        />

        <CodeSandboxWorkSpace generatedCode={generatedCode} />
      </div>
    </div>
  );
};
export default Project;
